name: 'Deploy'

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@3e282fcd55c8de21f232397e9fb876cd33e612f1 # v2.0.3

      - name: Install deps
        run: bun install

      - name: Build
        run: bun run build

      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@7bfa3a4717ef143a604ee0a99d859b8886a96d00 # v1.9.3
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          repositories: "static-website-gh-pages-sample"

      # TODO: ビルドとデプロイを別 Job 化

      # https://github.com/marketplace/actions/checkout
      - name: Checkout deploy website repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          repository: 'tatsutakein/static-website-gh-pages-sample'
          token: ${{ steps.app-token.outputs.token }}
          ref: 'gh-pages'
          path: 'deploy/website'

      - name: Copy deploy files
        run: |
          rm -rf deploy/website/*
          cp -a dist/. deploy/website

      - name: Push deploy repository
        run: |
          git config user.email "develop@tatsutakein.jp"
          git config user.name "tatsutakein"

          git add .
          git commit -m "Deploy from ${{ github.repository }} ${{ github.sha }}"
          git push origin gh-pages
        working-directory: deploy/website
